language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COVERALLS=1
    
    - php: 7.0
      env: PHPCS=1
  allow_failures:
    - env: COVERALLS=1

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

  - if [[ "$COVERALLS" == "1" ]]; then composer require --dev satooshi/php-coveralls:dev-master; fi
  - if [[ "$COVERALLS" == "1" ]]; then mkdir -p build/logs; fi

  - phpenv rehash

script:
  - if [[ "$PHPCS" == "1" ]]; then vendor/bin/phpcs -p --standard=PSR2 ./src ./tests; fi

  - if [[ "$PHPCS" != "1" ]]; then phpunit; fi

  - if [[ "$COVERALLS" == "1" ]]; then  vendor/bin/coveralls -v; fi
